In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [4]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [66]:
arr = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [3, 4, 5, 6]],
        [[21, 22, 23, 24], [25, 26, 27, 28], [6, 7, 8, 5]],
    ]
)
print(arr)

print("\n", arr.ndim)

print(arr.size)

np.min(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 3  4  5  6]]

 [[21 22 23 24]
  [25 26 27 28]
  [ 6  7  8  5]]]

 3
24


np.int64(1)

array([[25, 26, 27],
       [ 6,  7,  8]])

In [ ]:
arr1 = np.array([1, 2])

bool = arr1.astype(np.bool)
print(bool)
print(bool[::-1])
print(np.rev)

[ True  True]
[ True  True]


In [94]:
a = np.array([1, 2, 3, 4])
b = a.copy()
b[0] = 700

print(a)

[1 2 3 4]


In [98]:
np.sin(30)

np.float64(-0.9880316240928618)

In [10]:
A = np.array([[1, 2], [3, 4]])
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [99]:
arr1 = np.array([[[3, 1], [4, 2]]])
arr2 = np.array([[[6, 2], [7, 5]]])

# np.hstack(arr)
print(np.vstack((arr1, arr2)))

print(np.sort(arr1))
print(np.sort(arr2))

print(np.unique(arr1))

print(np.unique(arr2))

[[[3 1]
  [4 2]]

 [[6 2]
  [7 5]]]
[[[1 3]
  [2 4]]]
[[[2 6]
  [5 7]]]
[1 2 3 4]
[2 5 6 7]


In [12]:
arr = np.array([1, 2, 6.7, True])
arr2 = np.array(["a", 2, "b", "3"])
print("DType", arr.dtype)
print("DType", arr2.dtype)

DType float64
DType <U21


In [ ]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [105]:
l = [x for x in range(10)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [111]:
arr = np.arange(4)
print("Original Array:", arr)

reshape_arr = arr.reshape((2, 2))
print("Reshaped 2x2 Array:\n ", reshape_arr)

Original Array: [0 1 2 3]
Reshaped 2x2 Array:
  [[0 1]
 [2 3]]


In [15]:
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

shape = np.shape(my_array)
print(shape)

n_dimensions = np.ndim(my_array)
print(n_dimensions)

# size= np.itemsize(my_array)

# print(size)
print(my_array.itemsize)

(4, 2)
2
2


In [16]:
ones = np.ones(9)
print(ones)

reshape = ones.reshape((3, 3))
print(reshape)

convert = np.array([reshape], dtype=bool)
print(convert)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


TypeError: Cannot construct a dtype from an array

In [112]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

In [ ]:
zeros = np.zeros(5)
ones = np.ones(5)

print(zeros)
print(ones)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [119]:
# array = np.array(5,10)

value = np.linspace(5, 50, 10)
print(value)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [20]:
py_list = [1, 2, 3, 4, 5]
arr = np.array(py_list)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [128]:
arr = np.arange(10)
print(arr[::-1])

print(arr)
np.reversed(arr)
reversed(arr)

[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


AttributeError: module 'numpy' has no attribute 'reversed'

In [129]:
arr1 = np.array([1, 0, 0])

arr2 = np.array([0, 1, 0])

arr3 = np.array([0, 0, 1])

arr = np.vstack((arr1, arr2, arr3))

print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
arr = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr)

print("First Row: ", arr[0])

print("Last Column: ", arr[:, -1])

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First Row:  [1 2 3 4]
Last Column:  [ 4  8 12 16]


In [24]:
sampleArray = np.array(
    [
        [3, 6, 9, 12],
        [15, 18, 21, 24],
        [27, 30, 33, 36],
        [39, 42, 45, 48],
        [51, 54, 57, 60],
    ]
)

print(sampleArray)
print(np.stack(sampleArray[1::2, 0::2]))

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[15 21]
 [39 45]]


In [130]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


In [26]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)

print("First 2 rows and columns:\n", arr[0:2, 0:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First 2 rows and columns:
 [[1 2]
 [5 6]]


In [27]:
arr = np.arange(1, 11)
arr[arr % 2 == 1] = -1


print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [131]:
arr = np.array([1, 0, 2, 0, 3, 0, 4])
print("Array: ", arr)

print(np.nonzero(arr))

Array:  [1 0 2 0 3 0 4]
(array([0, 2, 4, 6]),)


In [ ]:
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])

common = np.intersect1d(a, b)
print(common)

[2 4 8]


In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum1 = np.sum([a, b], axis=0)
print(sum1)

multy = np.multiply(a, b)
print(multy)

[5 7 9]
[ 4 10 18]


In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dotp = np.dot(a, b)
print(dotp)

32


In [32]:
arr = np.array([10, 20, 30, 100, 200, 300])

print(np.mean(arr))
print(np.median(arr))

print(np.std(arr))

110.0
65.0
107.08252269472673


In [135]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

common = np.intersect1d(a, b)
delete = np.delete(a, 4)
print(a)
print(delete)

[1 2 3 4 5]
[1 2 3 4]


In [34]:
delete

array([1, 2, 3, 4])

In [35]:
arr = np.array([10, 20, 30, 40, 50])

origional_min = 10
origional_max = 50

normalized_array = (arr - origional_min) / (origional_max - origional_min)
print(normalized_array)

[0.   0.25 0.5  0.75 1.  ]


In [36]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])

match = a == b

np.where(match)

(array([0, 2]),)

In [37]:
arr = np.arange(15)

print(arr[5:11])

[ 5  6  7  8  9 10]


In [38]:
random = np.random.rand(3, 2)
print(random)
print(np.min(random))
print(np.max(random))

[[0.26278751 0.86837793]
 [0.93394933 0.18755736]
 [0.85802147 0.01579356]]
0.01579355548416772
0.9339493319785162


In [39]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])

print(sampleArray)

sorted = sampleArray[:, 1].argsort()
sorted_array = sampleArray[sorted]

print("Sorted array: \n", sorted_array)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorted array: 
 [[82 22 12]
 [34 43 73]
 [53 94 66]]


In [40]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
newColumnToAdd = np.array([10, 10, 10])

delete_column = np.delete(sampleArray, [1], axis=1)

print(delete_column)
insert_column = np.insert(delete_column, 1, newColumnToAdd, axis=1)
print("newColumnTAdd: \n", insert_column)

[[34 73]
 [82 12]
 [53 66]]
newColumnTAdd: 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


In [41]:
random = np.random.randint(1, 101, size=10)
print(random)

[87 58  5 87 33 56 55 94 92 20]


In [42]:
randomint = np.random.randint(1, 50, size=(3, 3))
print(randomint)
sort = np.sort(randomint, axis=1)
print("Sorted: \n", sort)

[[ 5 18 25]
 [36 20 18]
 [ 1 28 32]]
Sorted: 
 [[ 5 18 25]
 [18 20 36]
 [ 1 28 32]]


In [43]:
arr = np.arange(10)

print("Origional : ", arr)

shuffle_arr = np.random.shuffle(arr)

print("shuffled:", shuffle_arr)

Origional :  [0 1 2 3 4 5 6 7 8 9]
shuffled: None


In [44]:
ones = np.ones(25).reshape([5, 5])
print(ones)

ones[1:-1, 1:-1] = 0

print("\n", ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
a = np.array([1, 2, np.nan, 4, 5])

Nan = np.isnan(a)
print(np.any(Nan))

True


In [46]:
arr = np.array([[8, 4, 1], [5, 2, 7], [6, 9, 3]])

sorted = arr[::, 1].argsort()
# print(sorted)
newvalue = arr[sorted]
print(newvalue)

[[5 2 7]
 [8 4 1]
 [6 9 3]]


In [47]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

print("\n", arr)

print(arr.flatten())


 [[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [48]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vertical Stack: \n", np.vstack((a, b)))
print(np.hstack((a, b)))

Vertical Stack: 
 [[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [49]:
arr = np.arange(9)
print("Origional Array: ", arr)

print("Split", np.split(arr, 3))

Origional Array:  [0 1 2 3 4 5 6 7 8]
Split [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [50]:
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

addition = np.add(arrayOne, arrayTwo)
print(addition)

print(arrayOne + arrayTwo)

squaring = addition**2
print(squaring)

[[20 39 33]
 [25 25 28]]
[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


In [51]:
arr = np.array([[1, 2], [3, 4]])
print(np.invert(arr))

print(np.linalg.inv(arr))

[[-2 -3]
 [-4 -5]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [52]:
arr = np.array([5, 12, 29, 30, 44, 7, 18])

mask = arr < 30

value = arr[mask]
print(value)

[ 5 12 29  7 18]


In [53]:
arr = np.array([2, 3, 2, 5, 3, 3, 2, 5])

return_count = np.unique(arr, return_counts=True)
print(return_count)

(array([2, 3, 5]), array([3, 3, 2]))


In [54]:
a = np.array([1, 2, 3, 5, 7])
b = np.array([3, 4, 5, 6, 7])

print(np.intersect1d(a, b))
print(np.union1d(a, b))

[3 5 7]
[1 2 3 4 5 6 7]


In [55]:
arr = np.array([[1, 2], [3, 4]])

print(np.transpose(arr))

[[1 3]
 [2 4]]


In [56]:
A = np.array([[4, 2], [1, 3]])

print(np.linalg.eig(A))

EigResult(eigenvalues=array([5., 2.]), eigenvectors=array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]]))


In [57]:
A = np.array([[1, 2], [3, 4]])

B = np.array([8, 18])
print(np.linalg.solve(A, B))

[2. 3.]


In [58]:
arr = np.array([10, 20, 30, 100, 200, 300])
checkered = np.zeros([8, 8])

checkered[1::2, ::2] = 1
checkered[::2, 1::2] = 1
print(checkered)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [59]:
arr = np.array([1.5, 2.8, 3.2, 4.1])
value = 3

close = np.abs(arr - value).argmin()
print(arr[close])

2.8


In [242]:
zeros = np.zeros(9)
print(zeros)

reshape_h = zeros.reshape((3, 3))


reshape_h[0:1, 0:1] = 1
reshape_h[1:2, 1:2] = 1
reshape_h[2:3, 2:3] = 1
print(reshape_h)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
